
// <auto-generated/>
#nullable enable
#pragma warning disable CS0108 // hides inherited member
#pragma warning disable CS0162 // Unreachable code
#pragma warning disable CS0164 // This label has not been referenced
#pragma warning disable CS0219 // Variable assigned but never used
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
#pragma warning disable CS8601 // Possible null reference assignment
#pragma warning disable CS8602
#pragma warning disable CS8604 // Possible null reference argument for parameter
#pragma warning disable CS8619
#pragma warning disable CS8620
#pragma warning disable CS8631 // The type cannot be used as type parameter in the generic type or method
#pragma warning disable CS8765 // Nullability of type of parameter
#pragma warning disable CS9074 // The 'scoped' modifier of parameter doesn't match overridden or implemented member
#pragma warning disable CA1050 // Declare types in namespaces.

using System;
using MemoryPack;


/// <remarks>
/// MemoryPack GenerateType: Object<br/>
/// <code>
/// <b>int</b> X<br/>
/// <b>int</b> Y<br/>
/// <b>NodaTime.Instant</b> Now<br/>
/// </code>
/// </remarks>
partial record TestRequest : IMemoryPackable<TestRequest>, global::MemoryPack.IFixedSizeMemoryPackable
{

    static partial void StaticConstructor();

    static TestRequest()
    {
        global::MemoryPack.MemoryPackFormatterProvider.Register<TestRequest>();
        StaticConstructor();
    }

    [global::MemoryPack.Internal.Preserve]
    static int global::MemoryPack.IFixedSizeMemoryPackable.Size => 1 + System.Runtime.CompilerServices.Unsafe.SizeOf<int>() + System.Runtime.CompilerServices.Unsafe.SizeOf<int>() + System.Runtime.CompilerServices.Unsafe.SizeOf<global::NodaTime.Instant>();

    [global::MemoryPack.Internal.Preserve]
    static void IMemoryPackFormatterRegister.RegisterFormatter()
    {
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<TestRequest>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new global::MemoryPack.Formatters.MemoryPackableFormatter<TestRequest>());
        }
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<TestRequest[]>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new global::MemoryPack.Formatters.ArrayFormatter<TestRequest>());
        }

    }

    [global::MemoryPack.Internal.Preserve]
    static void IMemoryPackable<TestRequest>.Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer, scoped ref TestRequest? value) 
    {

        if (value == null)
        {
            writer.WriteNullObjectHeader();
            goto END;
        }

        writer.WriteUnmanagedWithObjectHeader(3, value.@X, value.@Y, value.@Now);

    END:

        return;
    }

    [global::MemoryPack.Internal.Preserve]
    static void IMemoryPackable<TestRequest>.Deserialize(ref MemoryPackReader reader, scoped ref TestRequest? value)
    {

        if (!reader.TryReadObjectHeader(out var count))
        {
            value = default!;
            goto END;
        }



        int __X;
        int __Y;
        global::NodaTime.Instant __Now;

        
        if (count == 3)
        {
            if (value == null)
            {
                reader.ReadUnmanaged(out __X, out __Y, out __Now);


                goto NEW;
            }
            else
            {
                __X = value.@X;
                __Y = value.@Y;
                __Now = value.@Now;

                reader.ReadUnmanaged(out __X);
                reader.ReadUnmanaged(out __Y);
                reader.ReadUnmanaged(out __Now);

                goto SET;
            }

        }
        else if (count > 3)
        {
            MemoryPackSerializationException.ThrowInvalidPropertyCount(typeof(TestRequest), 3, count);
            goto READ_END;
        }
        else
        {
            if (value == null)
            {
               __X = default!;
               __Y = default!;
               __Now = default!;
            }
            else
            {
               __X = value.@X;
               __Y = value.@Y;
               __Now = value.@Now;
            }


            if (count == 0) goto SKIP_READ;
            reader.ReadUnmanaged(out __X); if (count == 1) goto SKIP_READ;
            reader.ReadUnmanaged(out __Y); if (count == 2) goto SKIP_READ;
            reader.ReadUnmanaged(out __Now); if (count == 3) goto SKIP_READ;

    SKIP_READ:
            if (value == null)
            {
                goto NEW;
            }
            else
            {
                goto SET;
            }

        }

    SET:
        goto NEW;

        goto READ_END;

    NEW:
        value = new TestRequest(__X, __Y, __Now)
        {

        };

    READ_END:

    END:

        return;
    }
}
